### ISSUE TITLE
[Nullsafe Queries] Default values for Nullable<T> causing troubles

### ISSUE THREAD

**Issue by peterwurzinger** [axelheer/nein-linq#14]
Given the following example:

```cs
class Temporal {
    public DateTime? Date { get; }
}

class TemporalView {
    public DateTime? DateView { get; set; }
}

IQueryable<Temporal> query ...ToNullable();
query.Select(t => new TemporalView { DateView = t.Date.Value.AddDays(-1) });
```

It *looks* good, but at runtime things behave strange at first sight:
`DateView = Date.Value.AddDays(-1)` is an expression tree of Kind
- `Bind(DateView, MethodCall("AddDays", MemberAcces(MemberAccess(we, Date), Value)))`. 

NeinLinq prevents NR-exceptions to be thrown by inserting nullchecks and returning default values. 
When `Date` is null that leads to
- `Bind(DateView, Call("AddDays", MA(MA(we, Date), Value)))`
- reducing to `Bind(DateView, Call("AddDays", MA(null, Value)))`
- to `Bind(DateView, Call("AddDays", default(DateTime)))` where default(DateTime) is 01.01.0001
And subtracting a day from the minimum date will trigger an out-of-range-exception.

From a general point of view the main problem is, that the default value is determined by the most outer expression, while the expression gets evaluated from inside out.
One approach could be to pass the information whether an outer expression is nullable to every inner expression, and, if so, ommit their execution at appearance or return `null` while changing it's type.

1. `Bind(DateView, MethodCall("AddDays", MemberAcces(MemberAccess(we, "Date"), "Value")))` -> `Nullable<DateTime>`
2. `MethodCall("AddDays", MemberAcces(MemberAccess(we, "Date"), "Value"))` -> `DateTime`
3. `MemberAcces(MemberAccess(we, "Date"), "Value")` -> `DateTime`
4. `MemberAccess(we, "Date")` -> `Nullable<DateTime>`

Ad 1.: Expression is nullable, no action required
Ad 2.: An outer expression is nullable, omit execution or return null (change type?)
Ad 3.: An outer expression is nullable, omit execution or return null (change type?)
Ad 4.: Expression is nullable, no action required

There can't be every inner expression be affected by such a mechanism - e.g. method calls of extension methods but not arbitrary method calls.

I can't tell whether that solution is good, valid, or if it is even an issue. The point is, that above code would cause runtime exceptions nevertheless, but the question is which behavior is desirable instead. Just leaving this here for now.

**Comment by axelheer** [comment]
A slightly modified version of the given example:

```csharp
class Some {
    public DateTime Date { get; }
}

class Temporal {
    public Some Some { get; }
}

class TemporalView {
    public Some SomeView { get; set; }
}

IQueryable<Temporal> query ...ToNullable();
query.Select(t => new TemporalView { SomeView = t.Some.Date.AddDays(-1) });
```

Should lead to the same problem without using any nullables. Thus, we cannot reduce this issue to some special treatment of nullables. Every class is quite nullable too (whoever thought this's a good idea, but that's quite another story...)

On the other hand: the value can be 01.01.0001 anyway. It's a far fetched edge case, which may deserve some love anyway? An extension method `.TheDayBefore()` for `DateTime?` maybe...

Just my first thoughts. I'll need to give it some more thoughts another day.

**Comment by peterwurzinger** [comment]
For the sake of completeness, a possible workaround for the example above could be:


```cs
private static readonly Lazy<Func<DateTime?, DateTime?>> TheDayBeforeCompiled = new Lazy<Func<DateTime?, DateTime?>>(() => TheDayBeforeExpr().Compile());

[InjectLambda(nameof(TheDayBeforeExpr))]
public static DateTime? TheDayBefore(this DateTime? d)
{
    return TheDayBeforeCompiled.Value(d);
}

public static Expression<Func<DateTime?, DateTime?>> TheDayBeforeExpr()
{
    return d => d == null ? (DateTime?)null : d.Value.AddDays(-1);
}
```


used as

```cs
IQueryable<Temporal> query ...ToNullable();
query.Select(t => new TemporalView { DateView = t.Date.TheDayBefore() });
```

**Comment by axelheer** [comment]
Just another approach:

```csharp
private static readonly Lazy<Func<DateTime, DateTime>> TheDayBeforeCompiled = new Lazy<Func<DateTime, DateTime>>(() => TheDayBeforeExpr().Compile());

[InjectLambda(nameof(TheDayBeforeExpr))]
public static DateTime TheDayBefore(this DateTime d)
{
    return TheDayBeforeCompiled.Value(d);
}

public static Expression<Func<DateTime, DateTime>> TheDayBeforeExpr()
{
    return d => d <  default(DateTime).AddDays(1) ? default(DateTime) : d.Value.AddDays(-1);
}
```

Since null-safety isn't the issue here, but having negative dates is...
