### ISSUE TITLE
Query tags are stripped away

### ISSUE THREAD

**Issue by Arithmomaniac** [axelheer/nein-linq#21]
A simple query like `db.MyTable.ToInjectable().TagWith("MyTag").ToList();` does not include `-- MyTag` in the generated SQL, [as expected](https://docs.microsoft.com/en-us/ef/core/querying/tags).

I am using NeinLinq.EntityFrameworkCore 4.1.0 .

**Comment by peterwurzinger** [comment]
Have you tried using `db.MyTable.ToEntityInjectable()`? This exposes the EF Core internal query provider, and I would suspect `TagWith()` to check for the backing provider.

**Comment by Arithmomaniac** [comment]
That works. I guess it's handy for more than just async 🙂

**Comment by peterwurzinger** [comment]
If you need access to the EF Core query provider, then you will need to use `ToEntityInjectable`, which (kind of) preserves the original provider by wrapping it.

I just had a look on how `TagWith` is implemented. My assuption was correct, that it would check for the `Queryable.Provider` property to be an `EntityQueryProvider` (see https://github.com/dotnet/efcore/blob/main/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2932).
