### ISSUE TITLE
Is it possible to store the result of an expression in a property?

### ISSUE THREAD

**Issue by aescg1220** [axelheer/nein-linq#22]
We're using efcore and are attempting to find a solution that would satisfy storing the results of a calculated property directly in an ef entity.  Because our calculated values will rely on navigation properties, we'd like to store those back in the entity. Is this possible with nein-linq?

Here's a simple example:
```
public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
	public ICollection<FooBar> FooBars { get; set; }

	[NotMapped]
	[InjectLambda]
	public int FooBarCount { get; protected set; }
	public static Expression<Func<Foo, int>> FooBarCountExpr => foo => foo.FooBars.Count();
}

public class FooBar
{
	public int Id { get; set; }
	public Foo Foo { get; set; }
	public string Name { get; set; }
}
```

**Comment by axelheer** [comment]
Yeah, if you remove the protected setter of your property (nein-linq "injects" read-only properties only), that should do it.

**Comment by aescg1220** [comment]
I'm having trouble getting it to work with this code:

Class:
```
public class MyFoo
{
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int Id { get; set; }
	public string Name { get; set; }

	[NotMapped]
	[InjectLambda]
	public long TestInjection { get; }

	public static Expression<Func<MyFoo, long>> TestInjectionExpr => myFoo => myFoo.Id + 1;
}
```

Test:
```
[Fact]
public void TestFooInjection()
{
	UsingDbContext(db =>
	{
		var foo = new MyFoo()
		{
			Name = "Heythere",
		};

		db.MyFoos.Add(foo);
		db.SaveChanges();

		var fooResult = db.MyFoos.ToInjectable().First();
		fooResult.TestInjection.ShouldBeGreaterThan(0);

	});
}
```

**Comment by aescg1220** [comment]
Also I tried using ToEntityInjectable() and it's still returning 0 for the TestInjection property.

**Comment by axelheer** [comment]
Note to myself: don't answer any questions before second coffee...

NeinLinq intercepts during projection. Thus, without any LINQ query can't happen a thing. In order to use lampda injection you'll need some kind of projection to view models or the like.

I'll play with your use case next week or so, but I don't think there can be a LINQ based solution for this. Maybe implementing an EF Core based interceptor might help here?
