### ISSUE TITLE
Documentation: What does calling WithLambdaInjection() on DbContext options do?

### ISSUE THREAD

**Issue by mikastamm** [axelheer/nein-linq#26]
The following info from the readme is unclear to me:
> New: with Version 5.1.0 the package NeinLinq.EntityFrameworkCore introduced an explicit DbContext extension for enabling Lambda injection globally:
> 
>     services.AddDbContext<MyContext>(options =>
>          options.UseSqlOrTheLike("...").WithLambdaInjection());

Does this mean it is required to call WithLambdaInjection() on the DbContext?
Or does calling this mean I can use LamdaInjection on a IQueryable without calling q.ToInjectable() on it?

**Comment by axelheer** [comment]
> I can use LamdaInjection on a IQueryable without calling q.ToInjectable() on it

This.

**Comment by mikastamm** [comment]
Thats great, thank you!
