### ISSUE TITLE
Remark : functionality looks a bit like Linq.PropertyTranslator & QueryInterceptor

### ISSUE THREAD

**Issue by StefH** [axelheer/nein-linq#3]
This project looks a bit like:
https://github.com/StefH/Linq.PropertyTranslator.Core
together with
https://github.com/StefH/QueryInterceptor.Core

**Comment by axelheer** [comment]
I suppose you are referring to the "lambda injection" functionality of this project, which can replace any kind of `Func` within an expression tree, not just properties. Actually, the ability to "translate properties" has only been added recently (#2) and has not been released yet.

So, what's the point of this issue?

**Comment by StefH** [comment]
Not really an issue, just a remark. Sorry to bother you.

**Comment by axelheer** [comment]
Okay, no problem.
