### ISSUE TITLE
Doc bug

### ISSUE THREAD

**Issue by space-alien** [axelheer/nein-linq#31]
This example given in the docs does not compile due to the duplicate `Foo()` signature:

```cs
public class ParameterizedFunctions
{
    private readonly int narf;

    public ParameterizedFunctions(int narf)
    {
        this.narf = narf;
    }

    [InjectLambda]
    public string Foo()
    {
        ...
    }

    public Expression<Func<string>> Foo()
    {
        ... // use the narf!
    }
}
```

**Comment by axelheer** [comment]
It doesn't compile due to `...` either 😜

If `Foo` does not have any parameter, you need to give the "expression" sibling another name. I've updated this example accordingly. Thanks for the input!
