### ISSUE TITLE
How about an implicit cast to `CachedExpression<X>` from `Expression<X>`?

### ISSUE THREAD

**Issue by space-alien** [axelheer/nein-linq#32]
So that

```csharp
private static CachedExpression<Func<Character, bool>> IsVeryCleverExpr { get; }
    = new CachedExpression(c => c.Cleverness > 90);
```

Could become
```csharp
private static CachedExpression<Func<Character, bool>> IsVeryCleverExpr { get; }
    = c => c.Cleverness > 90;
```

**Comment by axelheer** [comment]
Yeah, that would look nice. Do you want to send a PR?

**Comment by space-alien** [comment]
With pleasure!

**Comment by space-alien** [comment]
I see that you the implicit cast from `Expression<X>` already exists, but the usage I propose is impossible, isn't it, because it would require the compiler to chain two implicit casts?

**Comment by axelheer** [comment]
Ahh, makes sense. Maybe I already tried it back then... 😳

**Comment by space-alien** [comment]
It was a fun little 30-minute rabbit hole for a Friday afternoon! 😅
