### ISSUE TITLE
ToInjectable vs ToEntityInjectable

### ISSUE THREAD

**Issue by strigefleur** [axelheer/nein-linq#34]
Having EntityFrameworkCore version of package just upgraded the app from .Net Core 5 to .Net Core 6.

Out of sudden queries with `ToEntityInjectable()` stopped working with translation error. Switching to `ToInjectable()` seems to fix the issue.

Is it me misinterpreting the docs or something's wrong?

**Comment by axelheer** [comment]
Which error?

**Comment by strigefleur** [comment]
```
The LINQ expression 'DbSet<MyModel>()
    // ... rest
    .Where(m => m.SomeDate.Date >= value && m.SomeDate.Date <= value2)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.
```

**Comment by axelheer** [comment]
Did you update your NuGet Packages too? The current NeinLinq version should work with the current .NET and EF version.

I'd need a small repro otherwise.

**Comment by strigefleur** [comment]
I did, NeinLinq is at 6.0.0, EFCore is at 6.0.5.

Will try to provide one tomorrow.
