### ISSUE TITLE
Issue with NeinLinq.EntityFramework, Linq.Count() method

### ISSUE THREAD

**Issue by TheHACKATHON** [axelheer/nein-linq#39]
Hi, I have a problem with the Count method in NeinLinq.EntityFramework

Framework: net4.8
EntityFramework: 6.4.4
NeinLinq: 6.1.1
NeinLinq.EntityFramework: 6.1.1

The code looks like this: 
I have a query provider: 
```csharp
public interface IQueryProvider<DbContext, TParam, TResult>
{
    [InjectLambda]
    IQueryable<TResult> GetQuery(DbContext context, TParam query);
}

public class GetTodoItemsQueryProvider : IQueryProvider<ApplicationDbContext, int, TodoItem>
{
    [InjectLambda(nameof(GetQueryExpression))]
    public IQueryable<TodoItem> GetQuery(ApplicationDbContext context, int query)
    {
        throw new NotImplementedException();
    }

    public Expression<Func<ApplicationDbContext, int, IQueryable<TodoItem>>> GetQueryExpression()
    {
        return (context, query) => from todoItem in context.Set<TodoItem>()
            where todoItem.ListId == query
            select todoItem;
    }
}
```

and code which query database and calls this query provider
```csharp
[HttpGet("test")]
public ActionResult Test()
{
    List<TodoItem> result = (from list in _dbContext.Set<TodoList>().ToDbInjectable()
        let item = _queryProvider.GetQuery(_dbContext, list.Id).FirstOrDefault()
        select item).ToList();

    int count = (from list in _dbContext.Set<TodoList>().ToDbInjectable()
        let item = _queryProvider.GetQuery(_dbContext, list.Id).FirstOrDefault()
        select item).Count();

  return true;
}
```

the first request(with ToList) works without any problems
on second request I got an exception 
```
LINQ to Entities does not recognize the method 'System.Data.Entity.DbSet`1[TodoList] Set[TodoList]()' method, and this method cannot be translated into a store expression.
```

Same code on NeinLinq.EntityFrameworkCore works fine, pls help

**Comment by TheHACKATHON** [comment]
Thanks for your research. 
`сontext.TodoItems` works as a workaround for now, but I would like to use Set<>, because in most code we inject abstract DbContext and don't have access to properties like TodoItems.

**Comment by axelheer** [comment]
Okay, after some further digging, it seems, that Entity Framework needs some processing, in order to understand, what you are doing here. This is currently implemented by an internal EF class `DbQueryVisitor`, which I now call using some Reflection.

I'm not quite happy with this "Hack", but please try Version 6.2.0 as it will be available as a Preview here:
https://github.com/axelheer/nein-linq/pkgs/nuget/NeinLinq.EntityFramework

For implementation details: 66817a24faa55fa9ab566b2ff94b6d3e710c802a

**Comment by TheHACKATHON** [comment]
For some reason, I can't see this prerelease on NuGet and can't install it via command
`NU1102: Unable to find package NeinLinq.EntityFramework with version (>= 6.2.0-preview.186)`

**Comment by axelheer** [comment]
It isn't on NuGet, the previews are on GitHub only.

See [Installing a package](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#installing-a-package) for details

**Comment by TheHACKATHON** [comment]
Thank you. I checked, for my cases the problem is fixed
