### ISSUE TITLE
Implement IDbAsyncQueryProvider

### ISSUE THREAD

**Issue by Luigi6821** [axelheer/nein-linq#42]
Hi,
using neinlinq with async operation I am getting the following error:

The provider for the source IQueryable doesn't implement IDbAsyncQueryProvider. Only providers that implement IDbAsyncQueryProvider can be used for Entity Framework asynchronous operations

Are you missing to Implement IDbAsyncQueryProvider interface?

PS: I am using EF 6.4.4

Thanks in advance !

**Comment by axelheer** [comment]
You have to use e.g. `ToDbInjectable` instead of `ToInjectable` in order to get the right implementation.
