### ISSUE TITLE
"UseSqlOrTheLike" method mentioned in README.md is nowhere to be found

### ISSUE THREAD

**Issue by marta-hryvniak-carne** [axelheer/nein-linq#48]
The following piece of documentation is confusing:

![image](https://github.com/axelheer/nein-linq/assets/145658498/efea2b8b-d154-4d22-9d39-e277c60bdf04)

There is no `UseSqlOrTheLike` method in the repo, no mention of it in Google.

**Comment by marta-hryvniak-carne** [comment]
Ok-ok. I get now that it was a placeholder.
Still, it is a confusing piece of documentation.

**Comment by axelheer** [comment]
I'm sure, it's not the only confusing part of the documentation. Feel free to submit some improvements.
