### ISSUE TITLE
Allow custom attribute provider for InjectLambdaAttribute

### ISSUE THREAD

**Issue by akarboush** [axelheer/nein-linq#49]
Currently, nein-linq uses `GetCustomAttribute` to retrieve the `InjectLambdaAttribute`. This approach creates two issues:

1. It requires the project containing the methods to be translated to have a dependency on nein-linq, which may not always be desirable or possible.
2. It limits the ability to translate methods from external libraries or third-party code where we can't add attributes.

## Proposed solution:
Since there is only one Attribute `InjectLambdaAttribute`  in the project we could add a static field to it to hold an optional custom attribute provider. 

## Points to consider:
- Should we allow multiple providers or just one?
- If multiple, how should conflicts be handled? or do we simply take the first match? (the order is important in this case)
- If single, should we prevent overwriting once set? (I think we should to prevent unintentionally overriding it)

Thr provider could be as simple as `Func<MemberInfo, InjectLambdaAttribute?>` when no order is required, otherwise a class or tupel with an order property.
I'd be happy to submit a PR for this feature if there's interest. Let me know if you'd like any clarification or have additional considerations for this proposal.

**Comment by axelheer** [comment]
I'd support just one provider. If necessary, you could replace the provider already in place with another one, which is free to call the original one for whatever reason... Or you could replace it with some kind of composite provider, calling other providers; no need to add too much complexity into the library here, I think.

Furthermore, we can also consider a non static approach. There is already an overload for a list of types to use purely by convention. What do you think about another overload for a custom provider? The downside would be, that you have to provide the provider (lol) within a completely different context.

I'm open for both approaches. And a PR would be very much appreciated.

**Comment by akarboush** [comment]
Yes, I agree regarding the non-static approach, while this could work well with the DbContextOptionsBuilder extension methods, since it is usually only called once in one place, it might be less convenient for the IQueryable `ToEntityInjectable` extension methods.

As you said, one provider is simpler IMO too. A public getter-only Provider with a SetProvider method will allow users to call the old provider if needed, as it's publicly accessible, and manage the order of the new one also.
