### ISSUE TITLE
Extending select functionality of Entity Framework

### ISSUE THREAD

**Issue by bdebaere** [axelheer/nein-linq#8]
Hi,

I was hoping to use your software to apply it to the following problem. Sadly it seems I get the same error: "The specified type member 'Test' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.".

Is there anything I'm doing wrong?

```csharp
    public class Status
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public int SortKey { get; set; }

        [InjectLambda]
        public string Test
        {
            get { return $"{Description} {SortKey}"; }
            set { }
        }
    }
```

```csharp
    dbSet
        .ToInjectable()
        .Select(s => new { s.Test })
        .ToList();
```

**Comment by axelheer** [comment]
Yeah, `[InjectLambda]` is only a hint, to find and insert the corresponding expression here. But there is no expression (you should get another error message, though).

Try something like this:

```csharp
public class Status
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int SortKey { get; set; }

    [InjectLambda]
    public string Test => TestExpr.Compile()(this); // or:  => throw new NotSupportedException();

    public static Expression<Func<Status, string>> TestExpr => s => string.Concat(s.Description, " ", s.SortKey);
}
```

Explanation: whenever *NeinLinq* detects some access to `.Test` it uses `.TestExpr` to retrieve the corresponding lambda expression to insert instead (!) of the actual access. This expression should be understandable for your LINQ provider ($"" may represent an issue here). Thus, `.Test` only executes w/o *NeinLinq* and can just throw some error, if not needed anywhere else.

**Comment by bdebaere** [comment]
That works indeed. But stops functioning as soon as I change it to the code below. This is necessary for OData. Do you have an idea why that might be? I can create a sample project if you want.

```csharp
[InjectLambda]
        public string Test {
            get { return TestExpr.Compile()(this); }
            set { } // This empty setter is necessary for OData to expose the property in an API.
        }
```

**Comment by axelheer** [comment]
Ah, makes sense, since *NeinLinq* only processes read-only properties (less overhead). By the way, can you use extensions methods or should it be properties?

We could introduce a feature flag (e.g. `.ToInjectable(honorWritableProperties: true)` to explicitly enable this, I think.

**Comment by bdebaere** [comment]
Before going down this road. I want to mention that the goal, if possible, would be to execute functions which allow statement bodies.

I notice that the Expression is still translated to SQL. What I hoped to accomplish was something like this (as an example of course). Adding extra properties (like a DTO) while remaining IQueryable<T> to allow related objects to be loaded. I realize the difficulty, if not impossibility, of this.

public class Status
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int SortKey { get; set; }

    [InjectLambda]
    public string Test => TestExpr.Compile()(this); // or:  => throw new NotSupportedException();

    public static Expression<Func<Status, string>> TestExpr => s =>
    {
        switch (s.Id) // Performing .Select(s => s.Test) should realize that Id is necessary for this.
        {
            case 1:
                return "1";
            case default:
                return "0";
        }
    };
}

**Comment by axelheer** [comment]
Does the example work? It should, but I'm not sure if this can be translated to SQL...

**Comment by bdebaere** [comment]
The code I wrote fails at compile time with error:
`A lambda expression with a statement body cannot be converted to an expression tree`

**Comment by axelheer** [comment]
Ah, totally forgot it's not possible. You could return different expressions based on other stuff, but that's much less than you are asking for...

**Comment by bdebaere** [comment]
Do you know if there would be a way to make this? My knowledge on expression trees and Entity Framework is too lacking. I would basically have to intercept where materialization takes place? But I'm not sure. They themselves have declared it a scenario they would not support.

I'll give another example of something more advanced so you can see the complexity I need.

```csharp
public class SalesFigures
{
    public List<Money> YearToMonthSalesRevenues
    {
        get
        {
             return YearlySalesFigures
                .Where(w => w.Year == DateTime.UtcNow.Year.ToString())
                .SelectMany(sm => sm.SalesRevenues)
                .GroupBy(
                    gb => gb.CurrencyCode,
                    (primaryKey, gb) => new Money { CurrencyCode = primaryKey, Value = gb.Sum(s => s.Value) })
                .ToList();
        }
        set { }
    }

    public List<YearlySalesFigure> YearlySalesFigures { get; set; }
}
```

**Comment by axelheer** [comment]
Your last example doesn't need any expression body and looks fine to me.

Regarding expression bodies: you have to "rephrase" your code in a more functional way, e.g. use `?:` operators instead of if-statements or linq operators instead of loops.

I'd suggest that you solve your general LINQ "issues" via StackOverflow or the like and come back when you still need this for writable properties.

**Comment by bdebaere** [comment]
I updated my code for a more complete view. Can you recheck please?

**Comment by axelheer** [comment]
You're breaking the "LINQ-chain". Calling `ToList()` executes the query; calling `AsQueryable()` on already "queried" and further processed data creates in-memory queries, which is not the same and probably not what you want. You really have to try to express this stuff as query, not imperative code, if this should go down to the database. Or it may be fine to process this in-memory, of course.

Your `DtoSalesFigures` seem the be a single object and not really a query? Maybe it should just be some kind of encapsulation providing access to the actual queries like `MonthlySalesFigures` and `YearlySalesFigures` and the other queries based on `YearlySalesFigures` or the like? Or some kind of builder/factory to create the actual queries based on further parameterization?

If you can break it down to a more simple but not too simple example I may be able to provide a more useful answer; but I might add, that this is not a general LINQ support forum...
