### ISSUE TITLE
Documentation: Can you explain the difference between classic and interactive queries

### ISSUE THREAD

**Issue by x2764tech** [axelheer/nein-linq#9]
Thank you for this library! It fixes a functionality gap that I have tried to overcome, and have never managed in so eloquent a way.

In the readme, you refer to "classic" and "interative" LINQ queries, but don't explain what the difference is. 

Would it be possible to add a note so that people like me (who clearly don't understand expression trees as fully as you) can understand the difference between the two?

Thanks

**Comment by axelheer** [comment]
Better?

**Comment by x2764tech** [comment]
That's great. Thank you!
